"""Terminal UI functions for the DataCloak auto-detection flow."""

import os
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from urllib.request import urlopen
from urllib.error import URLError

import yaml


_OLLAMA_BASE = "http://localhost:11434"


def check_ollama() -> bool:
    """Return True if Ollama is reachable at localhost:11434."""
    try:
        with urlopen(_OLLAMA_BASE, timeout=5):
            return True
    except (URLError, TimeoutError, OSError):
        return False


def display_proposed_config(detected: list[dict], skipped: list[dict], filename: str) -> None:
    """Print the proposed config table to stdout.

    Args:
        detected: List of dicts with column, type, confidence keys.
        skipped: List of dicts with column, type, confidence keys.
        filename: Name of the input CSV file.
    """
    print(f"\nDataCloak v1.1 — Auto-detected config for: {filename}")
    print("─" * 60)

    if detected:
        print(f"\n  WILL ANONYMIZE ({len(detected)} column{'s' if len(detected) != 1 else ''}):")
        for entry in detected:
            col = entry["column"]
            typ = entry["type"]
            conf = entry["confidence"]
            print(f"  ✓  {col:<20} →  {typ:<14} (confidence: {conf:.2f})")

    if skipped:
        print(f"\n  SKIPPED (low confidence):")
        for entry in skipped:
            col = entry["column"]
            conf = entry["confidence"]
            print(f"  ✗  {col:<20} →  {'???':<14} (confidence: {conf:.2f})")

    print()


def prompt_confirmation() -> str:
    """Prompt the user and return 'accept', 'edit', or 'quit'.

    Returns:
        One of 'accept', 'edit', or 'quit'.
    """
    while True:
        choice = input("  [A]ccept  [E]dit config before running  [Q]uit\n  > ").strip().lower()
        if choice in ("a", "accept"):
            return "accept"
        if choice in ("e", "edit"):
            return "edit"
        if choice in ("q", "quit"):
            return "quit"
        print("  Please enter A, E, or Q.")


def save_config_yaml(detected: list[dict], skipped: list[dict], filename: str, output_path: Path) -> None:
    """Save the detection results as a YAML config file.

    Args:
        detected: List of dicts with column, type, confidence keys.
        skipped: List of dicts with column, type, confidence keys.
        filename: Name of the source CSV file.
        output_path: Path to write the YAML file.
    """
    columns = {}
    for entry in detected:
        columns[entry["column"]] = {
            "type": entry["type"],
            "confidence": entry["confidence"],
        }

    skipped_section = {}
    for entry in skipped:
        skipped_section[entry["column"]] = {
            "confidence": entry["confidence"],
            "reason": "low_confidence",
        }

    data = {"columns": columns}
    if skipped_section:
        data["skipped"] = skipped_section

    timestamp = datetime.now().isoformat(timespec="seconds")
    header = (
        f"# DataCloak config — auto-generated by v1.1\n"
        f"# Source: {filename}\n"
        f"# Generated: {timestamp}\n"
        f"# To reuse: data-cloak --input {filename} --config {output_path.name}\n\n"
    )

    with open(output_path, "w") as f:
        f.write(header)
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)


def load_config_yaml(path: Path) -> dict:
    """Load column config from a YAML file.

    Args:
        path: Path to YAML config file.

    Returns:
        Dict mapping column name to field_type string,
        compatible with the anonymizer.
    """
    with open(path) as f:
        data = yaml.safe_load(f)
    columns = data.get("columns", {})
    return {col: entry["type"] if isinstance(entry, dict) else entry for col, entry in columns.items()}


def edit_config_in_editor(config_path: Path) -> dict:
    """Open a config file in $EDITOR and return the edited config.

    Args:
        config_path: Path to the YAML config to edit.

    Returns:
        Dict mapping column name to field_type string after user edits.
    """
    editor = os.environ.get("EDITOR", "nano")
    subprocess.run([editor, str(config_path)], check=True)
    return load_config_yaml(config_path)


def print_report(config: dict, row_count: int, skipped: list[dict]) -> None:
    """Print a summary report after anonymization.

    Args:
        config: Dict of column→type that was applied.
        row_count: Number of rows processed.
        skipped: List of skipped column dicts.
    """
    print(f"\n  Columns anonymized: {len(config)}")
    print(f"  Rows processed:     {row_count}")
    if skipped:
        names = ", ".join(e["column"] for e in skipped)
        print(f"  Skipped columns:    {names}")
    print()
